import random as rd
import time
t = time.time()
words = ['firm', 'expect', 'is', 'resulting', 'employing', 'first', 'policies', 'these', 'insufferable', 'understanding', 'increasingly', 'stroke', 'gives', 'phrase', 'form', 'trite', 'demonstrate', 'essentially', 'operating', 'team', 'strategy', 'not', 'process', 'linkedin', 'such', 'tinkering', 'context', 'being', 'apparent', 
'implementation', 'same', 'informed', 'devane', 'professor', 'catch', 'came', 'closely', 'will', 'where', 'oxford', 'piece', 'matter', 'expertise', 'each', 'get', 'box', 'phrases', 'some', 'mission', 'at', 'published', 'became', 'notes', 'university', 'bingo', 'expert', 'law', 'tiresome', 'people', 'slogan', 'business', 
'album', 'rise', 'meaning', 'buzzwords', 'today', 'big', 'and', 'time', 'evidence', 'recommendations', 'relating', 'importance', 'hires', 'student', 'cyber', 'fun', 'see', 'shorthands', 'popular', 'permeate', 'considered', 'part', 'british', 'readers', 'jargon', 'vocabulary', 'with', 'originate', 'points', 'bracketed', 
'patch', 'items', 'derive', 'help', 'contexts', 'drive', 'describe', 'moment', 'hallgren', 'can', 'synergy', 'a', 'cross', 'outside', 'determine', 'everyday', 'period', 'correct', 'there', 'perfect', 'wall', 'associated', 'different', 'intelligence', 'what', 'that', 'removed', 'information', 'performance', 'been', 'years',
'empty', 'businesses', 'song', 'r', 'date', 'privileges', 'focus', 'manager', 'publishes', 'experience', 'studying', 'hype', 'necessarily', 'lives', 'kreitner', 'enable', 'especially', 'contains', 'channels', 'said', 'answer', 'noticed', 'opted', 'long', 'group', 'fashionable', 'english', 'means', 'much', 'concise', 
'most', 'example', 'magisterial', 'but', 'against', 'collated', 'well', 'hit', 'known', 'them', 'particular', 'purposes', 'however', 'term', 'rapidly', 'existing', 'data', 'words', 'affect', 'print', 'like', 'called', 'authority', 'exclusively', 'page', 'quickly', 'america', 'must', 'thing', 'vertical', 'management', 
'terms', 'product', 'working', 'recall', 'hosts', 'find', 'board', 'an', 'generator', 'influence', 'annual', 'political', 'allows', 'own', 'instead', 'successful', 'life', 'ear', 'for', 'also', 'become', 'students', 'right', 'than', 'buzz', 'succeed', 'president', 'gresham', 'simply', 'examples', 'shortcuts', 'shadow',
'eschewing', 'usefulness', 'now', 'game', 'strong', 'street', 'creating', 'speech', 'culture', 'hyphenating', 'attempt', 'to', 'speak', 'corporate', 'politics', 'workplace', 'index', 'seen', 'internal', 'turn', 'tournament', 'passionate', 'played', 'keegan', 'appear', 'meeting', 'does', 'useful', 'on', 'coming', 
'cvs', 'of', 'feature', 'strategic', 'true', 'all', 'almost', 'becomes', 'cannot', 'journal', 'lose', 'from', 'results', 'buzzword', 'word', 'argued', 'harvard', 'technical', 
'trendy', 'rich', 'even', 'mode', 'responsible', 'already', 'specialized', 'this', 'just', 'whom', 'only', 'are', 'disciplines', 'so', 'which', 'acronyms', 'commonly', 'was', 'argument', 'subject', 'ideas', 'avoid', 'yankovic', 'operationalized', 'bad', 'producing', 'impress', 'were', 'thrive', 'conceptualized', 'overworked',
'other', 'score', 'the', 'seemed', 'prominently', 'poor', 'operate', 'by', 'another', 'better', 'problem', 'result', 'randomizer', 'control', 'defines', 'important', 'approaching', 'communication', 'many', 'spin', 'social', 'uses', 'statement', 'without', 'reasoned', 'out', 'pompous', 'origin', 'workplaces', 'introduction',
'include', 'robert', 'later', 'assemble', 'their', 'quicker', 'how', 'those', 'say', 'they', 'la', 'regard', 'created', 'presenters', 'use', 'studies', 'be', 'general', 'his', 'basketball', 's', 'highlight', 'in', 'innovative', 'or', 'year', 'characterized', 'sequence', 'original', 'forbes', 'record', 'organizational', 
'expressions', 'meaningless', 'asserted', 'yet', 'necessary', 'world', 'your', 'stated', 'reality', 'according', 'vice', 'it', 'players', 'creative', 'co', 'learn', 'put', 'artificial', 'structured', 'mandatory', 'top', 'then', 'analysis', 'manipulation', 'driven', 'within', 'generate', 'used', 'neologisms', 'up',
'accused', 'mutual', 'may', 'early', 'inspire', 'gain', 'media', 'digital', 'often', 'products', 'trend', 'csc', 'consulting', 'egos', 'entry', 'voguish', 'list', 'sense', 'rhetoric', 'realize', 'track', 'sum', 'jon', 'indeed', 'madness', 'sound', 'al', 'language', 'chic', 'has', 'employed', 'ticket', 'using', 'literary',
'new', 'when', 'do', 'problems', 'feel', 'retain', 'weiss', 'emphasize', 'radio', 'motivated', 'have', 'make', 'equivalent', 'good', 'television', 'more', 'during', 'extensive', 'into', 'could', 'if', 'nothing', 'debate', 'style', 'dynamic', 'playing', 'situation', 'timing', 'overused', 'weird', 'pop', 'dictionary', 'adapted',
 'way', 'might', 'field', 'hear', 'its', 'prepare', 'off', 'suit', 'as', 'fails', 'over', 'through', 'loaded', 'incentivize', 'things', 'others', 'evil', 'he', 'organization']
c = rd.choice(words)
print(c, words[471])